-- Load required elements:
INSERT INTO products.keywords.types(keyTypeName)
VALUES('Culture'),
      ('Diet'),
      ('Taste');

INSERT INTO products.keywords.defs(keyName, keyDesc, keyType)
VALUES('alcohol', 'Contains alcohol.', 'Diet'),
      ('allergen','Contains commonly known allergens (ie. peanuts, shellfish).', 'Diet'),
      ('meat','Contains animal proteins.', 'Diet'),
      ('fish','Contains protein primarily from fish/seafood.', 'Diet'),
      ('vegetarian','Mostly plant-based proteins or has vegetarian options. May contain dairy, honey, and/or egg products', 'Diet'),
      ('vegan','Vegan or vegan options. Entirely plant-based. No animal products.', 'Diet'),
      ('dairy','Contains dairy based ingredients.', 'Diet'),
      ('low-carb','Low-carb meal option.', 'Diet'),
      ('low-fat','This product is low in fat.', 'Diet'),
      ('gluten free','Does NOT contain gluten ingredients or has gluten-free options.', 'Diet'),
      ('sweet','Has more of a sweet taste.', 'Taste'),
      ('savory','Balanced salty and sweet flavor.', 'Taste'),
      ('spicy','Maybe a little spicy or has spicy options.', 'Taste'),
      ('hot','Considered hot by most or has very spicy options.', 'Taste'),
      ('American','American origin or style.)', 'Culture'),
      ('Asian','Asian origin or style.)', 'Culture'),
      ('European','European origin or style.)', 'Culture'),
      ('Mexican','Mexican origin or style.)', 'Culture'),
      ('Chinese','Chinese origin or style.)', 'Culture'),
      ('Indian','Indian origin or style.)', 'Culture'),
      ('Italian','Italian origin or style.)', 'Culture'),
      ('Greek','Greek origin or style.)', 'Culture'),
      ('French','French origin or style.)', 'Culture'),
      ('Middle Eastern','Middle Eastern origin or style.)', 'Culture');


INSERT INTO products.categories.defs(catID, catName, catDesc, catAvail)
VALUES(1, 'Breakfast', 'First meal.', 'Opening until noon.'),
     (2, 'Lunch', 'Middle meal.', '10am until 5pm, daily.'),
     (3, 'Dinner', 'Evening meal.', '4pm until close.'),
     (4, 'Dessert', 'Sweet Finale.', 'Any time of day!'),
     (5, 'Beverages', 'Something to drink?.', 'All day long.');

INSERT INTO products.categories.subcats(subcatName, fkCategory)
    VALUES ('Meals',1),
            ('Omelets',1),
            ('Sandwiches',1),
            ('Sides',1),
            ('Sandwiches',2),
            ('Tacos',2),
            ('Burritos',2),
            ('Soups',2),
            ('Salads',2),
            ('Entrees',3),
            ('Light Meals',3),
            ('A La Carte',3),
            ('Sinful',4),
            ('Sugar-Free',4),
           ('Wines',5),
           ('Juices',5),
           ('Soft Drinks',5),
           ('Dairy',5);

INSERT INTO products.options.defaults(defaultValue)
VALUES ('Selected'),
       ('None');

INSERT INTO products.options.types(optTypeValue)
VALUES ('Checkbox'),
       ('Radio'),
       ('Text');

-- Load optional demonstration data:
INSERT INTO products.options.defs(optName, optType, optDesc)
VALUES ('Sandwich_Options', 'Checkbox', 'Select your sandwich options.'),
       ('Bread', 'Radio', 'What type of bread would you like?'),
       ('Burger_Meat', 'Radio', 'How well would you like your protein cooked?'),
       ('Asian_Options', 'Radio', 'Select your meal options.'),
       ('Mexican_Options', 'Radio', 'Select your meal options.'),
       ('Italian_Options', 'Radio', 'Select your meal options.'),
       ('Spiciness', 'Radio', 'Select your meal options.'),
       ('Breakfast_Options', 'Checkbox', 'Select your breakfast options.'),
       ('Breakfast_Side', 'Radio', 'Choose a side.'),
       ('Lunch_Options', 'Checkbox', 'Select your lunch options.'),
       ('Lunch_Side', 'Radio', 'Choose a side.'),
       ('Dinner_Options', 'Checkbox', 'Select your dinner options.'),
       ('Dinner_Side', 'Radio', 'Choose a side.'),
       ('Cheese_Selection', 'Radio', 'Choose your cheese.'),
       ('Protein_Selection', 'Radio', 'Choose a protein'),
       ('Sauce', 'Radio', 'Choose a sauce.'),
       ('Dressing', 'Radio', 'Choose a dressing.'),
       ('Drink_Size', 'Radio', 'Choose drink size'),
       ('Notes_Requests', 'Text', 'Enter custom request here.');

INSERT INTO products.options.items(optItemValue, optItemName, optItemDefault, optCost)
VALUES('Sandwich_Options', 'Lettuce', 'Selected',0),
      ('Sandwich_Options', 'Tomato', 'Selected',0),
      ('Sandwich_Options', 'Onion', 'None',0),
      ('Sandwich_Options', 'Spicy Mustard', 'None',0.5),
      ('Burger_Meat', 'Rare', 'None',0),
      ('Burger_Meat', 'Medium', 'Selected',0),
      ('Burger_Meat', 'Medium-Well', 'None',0),
      ('Burger_Meat', 'Well Done', 'None',0),
      ('Bread', 'French', 'None',0),
      ('Bread', 'Sour Dough', 'None',0),
      ('Bread', 'Brioche', 'Selected',0),
      ('Bread', 'Rye', 'None',0),
      ('Bread', 'Whole Grain Wheat', 'None',0),
      ('Bread', 'Thick Tortilla', 'None',0),
      ('Asian_Options', 'Rice', 'Selected',0),
      ('Asian_Options', 'Noodles', 'None',0),
      ('Mexican_Options', 'Rice and Refried Beans', 'Selected',0),
      ('Mexican_Options', 'Salad and Black Beans', 'None',0),
      ('Mexican_Options', 'Chips, Salsa, and Guac', 'None',1),
      ('Italian_Options', 'Salad and Breadsticks',  'Selected',0),
      ('Italian_Options', 'Pizza Bread and Marinara ',  'None',1),
      ('Spiciness', 'Mild ',  'Selected',0),
      ('Spiciness', 'Medium ',  'None',0),
      ('Spiciness', 'Hot ',  'None',0),
      ('Breakfast_Options', 'Double Protein',  'None',2.5),
      ('Breakfast_Options', 'Coffee',  'None',3),
      ('Breakfast_Options', 'Syrup',  'None',0),
      ('Breakfast_Options', 'Fruit Jam',  'None',0),
      ('Breakfast_Options', 'Gravy',  'None',1),
      ('Breakfast_Side', 'Fruit',  'None',0),
      ('Breakfast_Side', 'Hashbrowns',  'None',0),
      ('Breakfast_Side', 'Pancakes',  'None',0),
      ('Lunch_Options', 'Pickle',  'None',0),
      ('Lunch_Options', 'Ketchup',  'None',0),
      ('Lunch_Side', 'Fries',  'Selected',0),
      ('Lunch_Side', 'Salad',  'None',0),
      ('Lunch_Side', 'Potato Salad',  'None',1),
      ('Lunch_Side', 'Soup',  'None',1),
      ('Lunch_Side', 'Tots',  'None',1),
      ('Lunch_Side', 'Onion Rings',  'None',1),
      ('Dinner_Options', 'Dinner Roll',  'None',0.50),
      ('Dinner_Options', 'Breadsticks',  'None',0.50),
      ('Dinner_Options', 'Pickle',  'Selected',0),
      ('Dinner_Side', 'Salad',  'Selected',0),
      ('Dinner_Side', 'Fries',  'None',0),
      ('Dinner_Side', 'Mashed Potatoes',  'None',0),
      ('Dinner_Side', 'Soup',  'None',0),
      ('Cheese_Selection', 'Cheddar',  'Selected',0),
      ('Cheese_Selection', 'American',  'None',0),
      ('Cheese_Selection', 'Swiss',  'None',0),
      ('Cheese_Selection', 'Bleu Cheese',  'None',0),
      ('Cheese_Selection', 'Vegan Cheddar',  'None',1),
      ('Protein_Selection', 'Ground Beef',  'None',0),
      ('Protein_Selection', 'Crispy Chicken',  'None',0),
      ('Protein_Selection', 'Tender Chicken',  'None',0),
      ('Protein_Selection', 'Impossible Burger',  'None',2),
      ('Sauce', 'Ranch',  'Selected',0),
      ('Sauce', 'Fry Sauce',  'None',0),
      ('Sauce', 'Honey Mustard',  'None',0),
      ('Sauce', 'Zesty Barbecue',  'None',0),
      ('Sauce', 'Salsa',  'None',1),
      ('Dressing', 'Thousand Island',  'None',0),
      ('Dressing', 'Ranch',  'Selected',0),
      ('Dressing', 'Italian',  'None',0),
      ('Drink_Size', 'Small',  'None',0),
      ('Drink_Size', 'Medium',  'Selected',1),
      ('Drink_Size', 'Large',  'None',2),
      ('Notes_Requests', 'Custom Request',  'None',0);

INSERT INTO products.list(productID, productName, productShort, productDesc,
                          productPrice, productImage, productCategory, productSubCategory)
VALUES (0,'','','',0,'',0,0),

INSERT INTO products.keywords(keyID, productID)
VALUES (0,0),

INSERT INTO products.options(optID, productID)
VALUES (0,0),